// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using evidenceKosmonautu.Database;

namespace evidenceKosmonautu.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("evidenceKosmonautu.Models.SuperheroModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("Jmeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Superheroes");
                });

            modelBuilder.Entity("evidenceKosmonautu.Models.SuperpowerModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.None);

                    b.Property<string>("Nazev")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Superschopnosti");
                });

            modelBuilder.Entity("evidenceKosmonautu.Models.jt_superhero_superpower", b =>
                {
                    b.Property<long>("SuperheroId")
                        .HasColumnType("bigint");

                    b.Property<long>("SuperpowerId")
                        .HasColumnType("bigint");

                    b.HasKey("SuperheroId", "SuperpowerId");

                    b.ToTable("jt_superhero_superpower");
                });

            modelBuilder.Entity("evidenceKosmonautu.Models.jt_superhero_superpower", b =>
                {
                    b.HasOne("evidenceKosmonautu.Models.SuperheroModel", "Superhero")
                        .WithMany("Superpowers")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("evidenceKosmonautu.Models.SuperpowerModel", "Superpower")
                        .WithMany("Superheroes")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Superhero");

                    b.Navigation("Superpower");
                });

            modelBuilder.Entity("evidenceKosmonautu.Models.SuperheroModel", b =>
                {
                    b.Navigation("Superpowers");
                });

            modelBuilder.Entity("evidenceKosmonautu.Models.SuperpowerModel", b =>
                {
                    b.Navigation("Superheroes");
                });
#pragma warning restore 612, 618
        }
    }
}
