// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using evidenceKosmonautu.Database;

namespace evidenceKosmonautu.Migrations
{
    [DbContext(typeof(MainContext))]
    partial class MainContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("evidenceKosmonautu.Models.SuperheroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Jmeno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prijmeni")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Superheroes");
                });

            modelBuilder.Entity("evidenceKosmonautu.Models.SuperpowerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nazev")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Superschopnosti");
                });

            modelBuilder.Entity("evidenceKosmonautu.Models.jt_superhero_superpower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SuperheroId")
                        .HasColumnType("int");

                    b.Property<int>("SuperpowerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SuperheroId");

                    b.HasIndex("SuperpowerId");

                    b.ToTable("jtHeroPower");
                });

            modelBuilder.Entity("evidenceKosmonautu.Models.jt_superhero_superpower", b =>
                {
                    b.HasOne("evidenceKosmonautu.Models.SuperheroModel", "SuperheroModel")
                        .WithMany("jtHeroPower")
                        .HasForeignKey("SuperheroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("evidenceKosmonautu.Models.SuperpowerModel", "SuperpowerModel")
                        .WithMany("jtHeroPower")
                        .HasForeignKey("SuperpowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SuperheroModel");

                    b.Navigation("SuperpowerModel");
                });

            modelBuilder.Entity("evidenceKosmonautu.Models.SuperheroModel", b =>
                {
                    b.Navigation("jtHeroPower");
                });

            modelBuilder.Entity("evidenceKosmonautu.Models.SuperpowerModel", b =>
                {
                    b.Navigation("jtHeroPower");
                });
#pragma warning restore 612, 618
        }
    }
}
